---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero
  require_chef_omnibus: 12.3.0

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[aar::default]
    attributes:
